global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true

  # Example email configuration (uncomment and configure as needed)
  # - name: 'email'
  #   email_configs:
  #     - to: 'admin@example.com'
  #       subject: '[HTTP Dispatcher] {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         Alert: {{ .Annotations.summary }}
  #         Description: {{ .Annotations.description }}
  #         {{ end }}

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - alertname
      - dev
      - instance